language: python
sudo: false
python:
  - "3.5"
env:
  - TOX_ENV=py35-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py27-django19
matrix:
  fast_finish: true

install:
  - pip install tox
  - pip install -U pytest
script:
  - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV
notifications:
  email:
    - connect2nazrul@gmail.com

matrix:
  allow_failures:
    - TOX_ENV=py35-django19
    - TOX_ENV=py34-django19

branches:
  only:
    - master
