language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - TOX_ENV="DJANGO_VERSION-110x"
  - TOX_ENV="DJANGO_VERSION-1101"
matrix:
  fast_finish: true

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install mock pathlib2; fi
  - pip install tox
  - pip install -U pytest
script:
  - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV
notifications:
  email:
    - connect2nazrul@gmail.com

matrix:
  allow_failures:
    - TOX_ENV=DJANGO_VERSION-1101

branches:
  only:
    - master
