language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TOX_ENV="DJANGO_VERSION-110x"
  - TOX_ENV="DJANGO_VERSION-1101"
matrix:
  fast_finish: true

install:
  - pip install tox
  - pip install -U pytest
script:
  - tox -e $TOX_ENV

before_script:
  - psql -c "CREATE USER hacs_admin WITH PASSWORD 'hacs_secret_^5$' CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE test_hacs_db OWNER hacs_admin TEMPLATE template1;" -U postgres

after_success:
    - pip install codecov
    - codecov -e TOX_ENV
addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

notifications:
  email:
    - connect2nazrul@gmail.com

matrix:
  allow_failures:
    - TOX_ENV=DJANGO_VERSION-1101

branches:
  only:
    - master
