# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacsgroupmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='hacspermissionmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='hacsrolemodel',
            name='name',
            field=models.CharField(db_index=True, max_length=127, unique=True),
        ),
    ]
