# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import hacs.fields
import hacs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hacs', '0002_routingtable_allowed_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingtable',
            name='generated_module',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Generated Module'),
        ),
        migrations.AlterField(
            model_name='routingtable',
            name='handlers',
            field=hacs.fields.DictField(blank=True, default='', null=True, validators=[hacs.validators.HttpHandlerValidator()], verbose_name='Handlers'),
        ),
        migrations.AlterField(
            model_name='routingtable',
            name='urls',
            field=hacs.fields.SequenceField(validators=[hacs.validators.UrlModulesValidator()], verbose_name='URLs'),
        ),
    ]
