# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacs', '0002_auto_20161130_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacsgroupmodel',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hacspermissionmodel',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hacspermissionmodel',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hacs_prm_children', related_query_name='hacs_prm_children_set', to='hacs.HacsPermissionModel'),
        ),
        migrations.AddField(
            model_name='hacsrolemodel',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
