# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacs', '0003_auto_20161205_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacsworkflowmodel',
            name='default_state',
            field=models.CharField(blank=True, default='draft', max_length=64),
        ),
    ]
