# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 17:31
from __future__ import unicode_literals

from django.db import migrations
import hacs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hacs', '0004_hacsworkflowmodel_default_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenttyperoutingrules',
            name='permissions',
        ),
        migrations.AddField(
            model_name='contenttyperoutingrules',
            name='permissions',
            field=hacs.fields.SequenceField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='hacscontenttype',
            name='permissions',
        ),
        migrations.AddField(
            model_name='hacscontenttype',
            name='permissions',
            field=hacs.fields.SequenceField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='hacsworkflowmodel',
            name='permissions',
        ),
        migrations.AddField(
            model_name='hacsworkflowmodel',
            name='permissions',
            field=hacs.fields.SequenceField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='routingtable',
            name='permissions',
        ),
        migrations.AddField(
            model_name='routingtable',
            name='permissions',
            field=hacs.fields.SequenceField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='siteroutingrules',
            name='permissions',
        ),
        migrations.AddField(
            model_name='siteroutingrules',
            name='permissions',
            field=hacs.fields.SequenceField(blank=True, null=True),
        ),
    ]
