---
- include: install_apt_packages.yml
# Required Directory Structure
- name: make sure project directory
  file: path="{{ hacs_deploypath_path }}" state="directory" force=false owner="ubuntu" group="ubuntu"

- name: make sure share directory is exists
  file: path="{{ hacs_deploypath_path }}/share" state="directory" recurse=yes force=no owner="ubuntu" group="ubuntu"

# Override some variables
- name: find psql executable path
  shell: "which psql"
  register: psql_path

- name: find python executable path
  shell: "which python"
  register: python_path

- name: find pip executable path
  shell: "which pip"
  register: pip_path

- name: find virtualenv executable path
  shell: "which virtualenv"
  register: virtualenv_path

- set_fact:
    postgresql_psql_executable: "{{ psql_path.stdout }}"
    python_executable: "{{ python_path.stdout }}"
    pip_executable: "{{ pip_path.stdout }}"
    virtualenv_executable: "{{ virtualenv_path.stdout }}"

- include: install_pip_packages.yml
