APT_KEYS:
  - {file: , id: , keyserver: , state: present, url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"}
  - {file: , id: , keyserver: , state: present, url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"}
