---
# This playbook constructs the whole application stack, to make developer ready.
- name: Construct HACS application stack
  hosts: hacs-dev
  become: true
  vars_files:
    - ./vars/common.yml
    - ./vars/apt_packages.yml
    - ./vars/apt_ppa.yml
    - ./vars/apt_keys.yml

  roles:
    - {role: pre_setup, tags: ["hacs_pre_setup"]}
    - {role: setup, tags: ["hacs_setup"]}
    - {role: post_setup, tags: ["hacs_post_setup"]}
